# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b16b3469d26809fca9b226dcae26b653bd362ab391ad794915c22c5764060700c1136696d68589bb6c43cea025b873fec3ea0a2435cbbe5d35eb20c4a63635eb

test:
  secret_key_base: 7c47b849e4297f12ec1bd416b2e7eef948f369dcb1a4f8ed9507081eabeef1fb79dc519af1986d1463d1c723949e0ac552c571de1cd529ebb0fd62e4d8e2ca75

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
